name: NoServerMessages
main: pro.marvin.minecraft.NoServerMessages
version: 1.0

commands:
  togglemessages:
    description: Toggle Join-/Leave-/Death-Messages on or off
    usage: Use /togglemessages to turn Join-/Leave-/Death-Messages on or off